package structs

import "database/sql"

type Batter struct {
	Season                 sql.NullString  `json:"Season" db:"Season"`
	Name                   sql.NullString  `json:"Name" db:"Name"`
	Team                   sql.NullString  `json:"Team" db:"Team"`
	Age                    sql.NullInt16   `json:"Age" db:"Age"`
	G                      sql.NullInt16   `json:"G" db:"G"`
	AB                     sql.NullInt16   `json:"AB" db:"AB"`
	PA                     sql.NullInt16   `json:"PA" db:"PA"`
	H                      sql.NullInt16   `json:"H" db:"H"`
	Single                 sql.NullInt16   `json:"Single" db:"Single"`
	Double                 sql.NullInt16   `json:"Double" db:"Double"`
	Triple                 sql.NullInt16   `json:"Triple" db:"Triple"`
	HR                     sql.NullInt16   `json:"HR" db:"HR"`
	R                      sql.NullInt16   `json:"R" db:"R"`
	RBI                    sql.NullInt16   `json:"RBI" db:"RBI"`
	BB                     sql.NullInt16   `json:"BB" db:"BB"`
	IBB                    sql.NullInt16   `json:"IBB" db:"IBB"`
	SO                     sql.NullInt16   `json:"SO" db:"SO"`
	HBP                    sql.NullFloat64 `json:"HBP" db:"HBP"`
	SF                     sql.NullFloat64 `json:"SF" db:"SF"`
	SH                     sql.NullFloat64 `json:"SH" db:"SH"`
	GDP                    sql.NullFloat64 `json:"GDP" db:"GDP"`
	SB                     sql.NullFloat64 `json:"SB" db:"SB"`
	CS                     sql.NullFloat64 `json:"CS" db:"CS"`
	AVG                    sql.NullFloat64 `json:"AVG" db:"AVG"`
	GB                     sql.NullFloat64 `json:"GB" db:"GB"`
	FB                     sql.NullFloat64 `json:"FB" db:"FB"`
	LD                     sql.NullFloat64 `json:"LD" db:"LD"`
	IFFB                   sql.NullFloat64 `json:"IFFB" db:"IFFB"`
	Pitches                sql.NullFloat64 `json:"Pitches" db:"Pitches"`
	Balls                  sql.NullFloat64 `json:"Balls" db:"Balls"`
	Strikes                sql.NullFloat64 `json:"Strikes" db:"Strikes"`
	IFH                    sql.NullFloat64 `json:"IFH" db:"IFH"`
	BU                     sql.NullFloat64 `json:"BU" db:"BU"`
	BUH                    sql.NullFloat64 `json:"BUH" db:"BUH"`
	BB_percent             sql.NullFloat64 `json:"BB%" db:"BB_percent"`
	K_percent              sql.NullFloat64 `json:"K_percent" db:"K_percent"`
	BB_per_K               sql.NullFloat64 `json:"BB/K" db:"BB_per_K"`
	OBP                    sql.NullFloat64 `json:"OBP" db:"OBP"`
	SLG                    sql.NullFloat64 `json:"SLG" db:"SLG"`
	OPS                    sql.NullFloat64 `json:"OPS" db:"OPS"`
	ISO                    sql.NullFloat64 `json:"ISO" db:"ISO"`
	BABIP                  sql.NullFloat64 `json:"BABIP" db:"BABIP"`
	GB_per_FB              sql.NullFloat64 `json:"GB_/FB" db:"GB_per_FB"`
	LD_percent             sql.NullFloat64 `json:"LD%" db:"LD_percent"`
	GB_percent             sql.NullFloat64 `json:"GB%" db:"GB_percent"`
	FB_percent             sql.NullFloat64 `json:"FB%" db:"FB_percent"`
	IFFB_percent           sql.NullFloat64 `json:"IFFB%" db:"IFFB_percent"`
	HR_per_FB              sql.NullFloat64 `json:"HR_per_FB" db:"HR_per_FB"`
	IFH_percent            sql.NullFloat64 `json:"IFH%" db:"IFH_percent"`
	BUH_percent            sql.NullFloat64 `json:"BUH%" db:"BUH_percent"`
	WOBA                   sql.NullFloat64 `json:"wOBA" db:"wOBA"`
	WRAA                   sql.NullFloat64 `json:"wRAA" db:"wRAA"`
	WRC                    sql.NullFloat64 `json:"wRC" db:"wRC"`
	Bat                    sql.NullFloat64 `json:"Bat" db:"Bat"`
	Fld                    sql.NullFloat64 `json:"Fld" db:"Fld"`
	Rep                    sql.NullFloat64 `json:"Rep" db:"Rep"`
	Pos                    sql.NullFloat64 `json:"Pos" db:"Pos"`
	RAR                    sql.NullFloat64 `json:"RAR" db:"RAR"`
	WAR                    sql.NullFloat64 `json:"WAR" db:"WAR"`
	Dol                    sql.NullString  `json:"Dol" db:"Dol"`
	Spd                    sql.NullFloat64 `json:"Spd" db:"Spd"`
	WRC_plus               sql.NullFloat64 `json:"wRC+" db:"wRC_plus"`
	WPA                    sql.NullFloat64 `json:"WPA" db:"WPA"`
	Plus_WPA               sql.NullFloat64 `json:"plus_WPA" db:"plus_WPA"`
	RE24                   sql.NullFloat64 `json:"RE24" db:"RE24"`
	REW                    sql.NullFloat64 `json:"REW" db:"REW"`
	PLI                    sql.NullFloat64 `json:"pLI" db:"pLI"`
	PhLI                   sql.NullFloat64 `json:"phLI" db:"phLI"`
	PH                     sql.NullFloat64 `json:"PH" db:"PH"`
	WPA_per_LI             sql.NullFloat64 `json:"WPA/LI" db:"WPA_per_LI"`
	Clutch                 sql.NullFloat64 `json:"Clutch" db:"Clutch"`
	FBv                    sql.NullFloat64 `json:"FBv" db:"FBv"`
	SL_percent             sql.NullFloat64 `json:"SL%" db:"SL_percent"`
	SLv                    sql.NullFloat64 `json:"SLv" db:"SLv"`
	CT_percent             sql.NullFloat64 `json:"CT%" db:"CT_percent"`
	CTv                    sql.NullFloat64 `json:"CTv" db:"CTv"`
	CB_percent             sql.NullFloat64 `json:"CB%" db:"CB_percent"`
	CBv                    sql.NullFloat64 `json:"CBv" db:"CBv"`
	CH_percent             sql.NullFloat64 `json:"CH%" db:"CH_percent"`
	CHv                    sql.NullFloat64 `json:"CHv" db:"CHv"`
	SF_percent             sql.NullFloat64 `json:"SF%" db:"SF_percent"`
	SFv                    sql.NullFloat64 `json:"SFv" db:"SFv"`
	KN_percent             sql.NullFloat64 `json:"KN%" db:"KN_percent"`
	KNv                    sql.NullFloat64 `json:"KNv" db:"KNv"`
	XX_percent             sql.NullFloat64 `json:"XX%" db:"XX_percent"`
	PO_percent             sql.NullFloat64 `json:"PO%" db:"PO_percent"`
	WFB                    sql.NullFloat64 `json:"wFB" db:"wFB"`
	WSL                    sql.NullFloat64 `json:"wSL" db:"wSL"`
	WCT                    sql.NullFloat64 `json:"wCT" db:"wCT"`
	WCB                    sql.NullFloat64 `json:"wCB" db:"wCB"`
	WCH                    sql.NullFloat64 `json:"wCH" db:"wCH"`
	WSF                    sql.NullFloat64 `json:"wSF" db:"wSF"`
	WKN                    sql.NullFloat64 `json:"wKN" db:"wKN"`
	WFB_per_C              sql.NullFloat64 `json:"wFB/C" db:"wFB_per_C"`
	WSL_per_C              sql.NullFloat64 `json:"wSL/C" db:"wSL_per_C"`
	WCT_per_C              sql.NullFloat64 `json:"wCT/C" db:"wCT_per_C"`
	WCB_per_C              sql.NullFloat64 `json:"wCB/C" db:"wCB_per_C"`
	CH_per_C               sql.NullFloat64 `json:"wCH/C" db:"wCH_per_C"`
	WSF_per_C              sql.NullFloat64 `json:"wSF/C" db:"wSF_per_C"`
	WKN_per_C              sql.NullFloat64 `json:"wKN/C" db:"wKN_per_C"`
	OSwing_percent         sql.NullFloat64 `json:"OSwing%" db:"OSwing_percent"`
	ZSwing_percent         sql.NullFloat64 `json:"ZSwing%" db:"ZSwing_percent"`
	Swing_percent          sql.NullFloat64 `json:"Swing_%" db:"Swing_percent"`
	OContact_percent       sql.NullFloat64 `json:"OContact%" db:"OContact_percent"`
	ZContact_percent       sql.NullFloat64 `json:"ZContact%" db:"ZContact_percent"`
	Contact_percent        sql.NullFloat64 `json:"Contact_percent" db:"Contact_percent"`
	Zone_percent           sql.NullFloat64 `json:"Zone_percent" db:"Zone_percent"`
	FStrike_percent        sql.NullFloat64 `json:"FStrike_percent" db:"FStrike_percent"`
	SwStr_percent          sql.NullFloat64 `json:"SwStr_percent" db:"SwStr_percent"`
	BsR                    sql.NullFloat64 `json:"BsR" db:"BsR"`
	Pace                   sql.NullFloat64 `json:"Pace" db:"Pace"`
	Def                    sql.NullFloat64 `json:"Def" db:"Def"`
	WSB                    sql.NullFloat64 `json:"wSB" db:"wSB"`
	UBR                    sql.NullFloat64 `json:"UBR" db:"UBR"`
	Age_Rng                sql.NullString  `json:"Age Rng" db:"Age Rng"`
	Off                    sql.NullFloat64 `json:"Off" db:"Off"`
	Lg                     sql.NullFloat64 `json:"Lg" db:"Lg"`
	WGDP                   sql.NullFloat64 `json:"wGDP" db:"wGDP"`
	Pull_percent           sql.NullFloat64 `json:"Pull_percent" db:"Pull_percent"`
	Cent_percent           sql.NullFloat64 `json:"Cent_percent" db:"Cent_percent"`
	Oppo_percent           sql.NullFloat64 `json:"Oppo_percent" db:"Oppo_percent"`
	Soft_percent           sql.NullFloat64 `json:"Soft_percent" db:"Soft_percent"`
	Med_percent            sql.NullFloat64 `json:"Med_percent" db:"Med_percent"`
	Hard_percent           sql.NullFloat64 `json:"Hard_percent" db:"Hard_percent"`
	TTO_percent            sql.NullFloat64 `json:"TTO_percent" db:"TTO_percent"`
	FRM                    sql.NullFloat64 `json:"FRM" db:"FRM"`
	AVG_plus               sql.NullFloat64 `json:"AVG_plus" db:"AVG_plus"`
	BB_percent_plus        sql.NullFloat64 `json:"BB_percent_plus" db:"BB_percent_plus"`
	K_percent_plus         sql.NullFloat64 `json:"K_percent_plus" db:"K_percent_plus"`
	OBP_plus               sql.NullFloat64 `json:"OBP_plus" db:"OBP_plus"`
	SLG_plus               sql.NullFloat64 `json:"SLG_plus" db:"SLG_plus"`
	ISO_plus               sql.NullFloat64 `json:"ISO_plus" db:"ISO_plus"`
	BABIP_plus             sql.NullFloat64 `json:"BABIP_plus" db:"BABIP_plus"`
	LD_plus_percent        sql.NullFloat64 `json:"LD_plus_percent" db:"LD_plus_percent"`
	GB_percent_plus        sql.NullFloat64 `json:"GB_percent_plus" db:"GB_percent_plus"`
	FB_percent_plus        sql.NullFloat64 `json:"FB_percent_plus" db:"FB_percent_plus"`
	HR_per_FB_percent_plus sql.NullFloat64 `json:"HR_per_FB_percent_plus" db:"HR_per_FB_percent_plus"`
	Pull_percent_plus      sql.NullFloat64 `json:"Pull_percent_plus" db:"Pull_percent_plus"`
	Cent_percent_plus      sql.NullFloat64 `json:"Cent_percent_plus" db:"Cent_percent_plus"`
	Oppo_percent_plus      sql.NullFloat64 `json:"Oppo_percent_plus" db:"Oppo_percent_plus"`
	Soft_percent_plus      sql.NullFloat64 `json:"Soft_percent_plus" db:"Soft_percent_plus"`
	Med_percent_plus       sql.NullFloat64 `json:"Med_percent_plus" db:"Med_percent_plus"`
	Hard_percent_plus      sql.NullFloat64 `json:"Hard_percent_plus" db:"Hard_percent_plus"`
	EV                     sql.NullFloat64 `json:"EV" db:"EV"`
	LA                     sql.NullFloat64 `json:"LA" db:"LA"`
	Barrels                sql.NullFloat64 `json:"Barrels" db:"Barrels"`
	Barrel_percent         sql.NullFloat64 `json:"Barrel_percent" db:"Barrel_percent"`
	MaxEV                  sql.NullFloat64 `json:"maxEV" db:"maxEV"`
	HardHit                sql.NullFloat64 `json:"HardHit" db:"HardHit"`
	HardHit_percent        sql.NullFloat64 `json:"HardHit_percent" db:"HardHit_percent"`
	CStr_percent           sql.NullFloat64 `json:"CStr_percent" db:"CStr_percent"`
	CSW_percent            sql.NullFloat64 `json:"CSW_percent" db:"CSW_percent"`
	XBA                    sql.NullFloat64 `json:"xBA" db:"xBA"`
	XSLG                   sql.NullFloat64 `json:"xSLG" db:"xSLG"`
	XwOBA                  sql.NullFloat64 `json:"xwOBA" db:"xwOBA"`
}

type Pitcher struct {
	Idfg                     sql.NullFloat64 `db:"IDfg" json:"IDfg"`
	Season                   sql.NullInt64   `db:"Season" json:"Season"`
	Name                     sql.NullString  `db:"Name" json:"Name"`
	Team                     sql.NullString  `db:"Team" json:"Team"`
	Age                      sql.NullInt64   `db:"Age" json:"Age"`
	W                        sql.NullInt64   `db:"W" json:"W"`
	L                        sql.NullInt64   `db:"L" json:"L"`
	War                      sql.NullFloat64 `db:"WAR" json:"WAR"`
	Era                      sql.NullFloat64 `db:"ERA" json:"ERA"`
	G                        sql.NullInt64   `db:"G" json:"G"`
	Gs                       sql.NullInt64   `db:"GS" json:"GS"`
	Cg                       sql.NullInt64   `db:"CG" json:"CG"`
	Sho                      sql.NullInt64   `db:"ShO" json:"ShO"`
	Sv                       sql.NullInt64   `db:"SV" json:"SV"`
	Bs                       sql.NullFloat64 `db:"BS" json:"BS"`
	Ip                       sql.NullFloat64 `db:"IP" json:"IP"`
	Tbf                      sql.NullFloat64 `db:"TBF" json:"TBF"`
	H                        sql.NullFloat64 `db:"H" json:"H"`
	R                        sql.NullFloat64 `db:"R" json:"R"`
	Er                       sql.NullFloat64 `db:"ER" json:"ER"`
	Hr                       sql.NullFloat64 `db:"HR" json:"HR"`
	Bb                       sql.NullFloat64 `db:"BB" json:"BB"`
	Ibb                      sql.NullFloat64 `db:"IBB" json:"IBB"`
	Hbp                      sql.NullFloat64 `db:"HBP" json:"HBP"`
	Wp                       sql.NullFloat64 `db:"WP" json:"WP"`
	Bk                       sql.NullFloat64 `db:"BK" json:"BK"`
	So                       sql.NullFloat64 `db:"SO" json:"SO"`
	Gb                       sql.NullFloat64 `db:"GB" json:"GB"`
	Fb                       sql.NullFloat64 `db:"FB" json:"FB"`
	Ld                       sql.NullFloat64 `db:"LD" json:"LD"`
	Iffb                     sql.NullFloat64 `db:"IFFB" json:"IFFB"`
	Balls                    sql.NullFloat64 `db:"Balls" json:"Balls"`
	Strikes                  sql.NullFloat64 `db:"Strikes" json:"Strikes"`
	Pitches                  sql.NullFloat64 `db:"Pitches" json:"Pitches"`
	Rs                       sql.NullFloat64 `db:"RS" json:"RS"`
	Ifh                      sql.NullFloat64 `db:"IFH" json:"IFH"`
	Bu                       sql.NullFloat64 `db:"BU" json:"BU"`
	Buh                      sql.NullFloat64 `db:"BUH" json:"BUH"`
	K_per_9                  sql.NullFloat64 `db:"K/9" json:"K/9"`
	Bb_per_9                 sql.NullFloat64 `db:"BB/9" json:"BB/9"`
	K_per_bb                 sql.NullFloat64 `db:"K/BB" json:"K/BB"`
	H_per_9                  sql.NullFloat64 `db:"H/9" json:"H/9"`
	Hr_per_9                 sql.NullFloat64 `db:"HR/9" json:"HR/9"`
	Avg                      sql.NullFloat64 `db:"AVG" json:"AVG"`
	Whip                     sql.NullFloat64 `db:"WHIP" json:"WHIP"`
	Babip                    sql.NullFloat64 `db:"BABIP" json:"BABIP"`
	Lob_percent              sql.NullFloat64 `db:"LOB%" json:"LOB%"`
	Fip                      sql.NullFloat64 `db:"FIP" json:"FIP"`
	Gb_per_fb                sql.NullFloat64 `db:"GB/FB" json:"GB/FB"`
	Ld_percent               sql.NullFloat64 `db:"LD%" json:"LD%"`
	Gb_percent               sql.NullFloat64 `db:"GB%" json:"GB%"`
	Fb_percent               sql.NullFloat64 `db:"FB%" json:"FB%"`
	Iffb_percent             sql.NullFloat64 `db:"IFFB%" json:"IFFB%"`
	Hr_per_fb                sql.NullFloat64 `db:"HR/FB" json:"HR/FB"`
	Ifh_percent              sql.NullFloat64 `db:"IFH%" json:"IFH%"`
	Buh_percent              sql.NullFloat64 `db:"BUH%" json:"BUH%"`
	Starting                 sql.NullFloat64 `db:"Starting" json:"Starting"`
	Start_minues_ip          sql.NullFloat64 `db:"Start-IP" json:"Start-IP"`
	Relieving                sql.NullFloat64 `db:"Relieving" json:"Relieving"`
	Relief_minues_ip         sql.NullFloat64 `db:"Relief-IP" json:"Relief-IP"`
	Rar                      sql.NullFloat64 `db:"RAR" json:"RAR"`
	Dollars                  sql.NullString  `db:"Dollars" json:"Dollars"`
	Tera                     sql.NullFloat64 `db:"tERA" json:"tERA"`
	Xfip                     sql.NullFloat64 `db:"xFIP" json:"xFIP"`
	Wpa                      sql.NullFloat64 `db:"WPA" json:"WPA"`
	Pluswpa                  sql.NullFloat64 `db:"+WPA" json:"+WPA"`
	Re24                     sql.NullFloat64 `db:"RE24" json:"RE24"`
	Rew                      sql.NullFloat64 `db:"REW" json:"REW"`
	Pli                      sql.NullFloat64 `db:"pLI" json:"pLI"`
	Inli                     sql.NullFloat64 `db:"inLI" json:"inLI"`
	Gmli                     sql.NullFloat64 `db:"gmLI" json:"gmLI"`
	Exli                     sql.NullFloat64 `db:"exLI" json:"exLI"`
	Pulls                    sql.NullFloat64 `db:"Pulls" json:"Pulls"`
	Wpa_per_li               sql.NullFloat64 `db:"WPA/LI" json:"WPA/LI"`
	Clutch                   sql.NullFloat64 `db:"Clutch" json:"Clutch"`
	Fb_percent2              sql.NullFloat64 `db:"FB%2" json:"FB%2"`
	Fbv                      sql.NullFloat64 `db:"FBv" json:"FBv"`
	Sl_percent               sql.NullFloat64 `db:"SL%" json:"SL%"`
	Slv                      sql.NullFloat64 `db:"SLv" json:"SLv"`
	Ct_percent               sql.NullFloat64 `db:"CT%" json:"CT%"`
	Ctv                      sql.NullFloat64 `db:"CTv" json:"CTv"`
	Cb_percent               sql.NullFloat64 `db:"CB%" json:"CB%"`
	Cbv                      sql.NullFloat64 `db:"CBv" json:"CBv"`
	Ch_percent               sql.NullFloat64 `db:"CH%" json:"CH%"`
	Chv                      sql.NullFloat64 `db:"CHv" json:"CHv"`
	Sf_percent               sql.NullFloat64 `db:"SF%" json:"SF%"`
	Sfv                      sql.NullFloat64 `db:"SFv" json:"SFv"`
	Kn_percent               sql.NullFloat64 `db:"KN%" json:"KN%"`
	Knv                      sql.NullFloat64 `db:"KNv" json:"KNv"`
	Xx_percent               sql.NullFloat64 `db:"XX%" json:"XX%"`
	Po_percent               sql.NullFloat64 `db:"PO%" json:"PO%"`
	Wfb                      sql.NullFloat64 `db:"wFB" json:"wFB"`
	Wsl                      sql.NullFloat64 `db:"wSL" json:"wSL"`
	Wct                      sql.NullFloat64 `db:"wCT" json:"wCT"`
	Wcb                      sql.NullFloat64 `db:"wCB" json:"wCB"`
	Wch                      sql.NullFloat64 `db:"wCH" json:"wCH"`
	Wsf                      sql.NullFloat64 `db:"wSF" json:"wSF"`
	Wkn                      sql.NullFloat64 `db:"wKN" json:"wKN"`
	Wfb_per_c                sql.NullFloat64 `db:"wFB/C" json:"wFB/C"`
	Wsl_per_c                sql.NullFloat64 `db:"wSL/C" json:"wSL/C"`
	Wct_per_c                sql.NullFloat64 `db:"wCT/C" json:"wCT/C"`
	Wcb_per_c                sql.NullFloat64 `db:"wCB/C" json:"wCB/C"`
	Wch_per_c                sql.NullFloat64 `db:"wCH/C" json:"wCH/C"`
	Wsf_per_c                sql.NullFloat64 `db:"wSF/C" json:"wSF/C"`
	Wkn_per_c                sql.NullFloat64 `db:"wKN/C" json:"wKN/C"`
	O_minues_swing_percent   sql.NullFloat64 `db:"O-Swing%" json:"O-Swing%"`
	Z_minues_swing_percent   sql.NullFloat64 `db:"Z-Swing%" json:"Z-Swing%"`
	Swing_percent            sql.NullFloat64 `db:"Swing%" json:"Swing%"`
	O_minues_contact_percent sql.NullFloat64 `db:"O-Contact%" json:"O-Contact%"`
	Z_minues_contact_percent sql.NullFloat64 `db:"Z-Contact%" json:"Z-Contact%"`
	Contact_percent          sql.NullFloat64 `db:"Contact%" json:"Contact%"`
	Zone_percent             sql.NullFloat64 `db:"Zone%" json:"Zone%"`
	F_minues_strike_percent  sql.NullFloat64 `db:"F-Strike%" json:"F-Strike%"`
	Swstr_percent            sql.NullFloat64 `db:"SwStr%" json:"SwStr%"`
	Hld                      sql.NullFloat64 `db:"HLD" json:"HLD"`
	Sd                       sql.NullFloat64 `db:"SD" json:"SD"`
	Md                       sql.NullFloat64 `db:"MD" json:"MD"`
	Era_minues_              sql.NullFloat64 `db:"ERA-" json:"ERA-"`
	Fip_minues_              sql.NullFloat64 `db:"FIP-" json:"FIP-"`
	Xfip_minues_             sql.NullFloat64 `db:"xFIP-" json:"xFIP-"`
	K_percent                sql.NullFloat64 `db:"K%" json:"K%"`
	Bb_percent               sql.NullFloat64 `db:"BB%" json:"BB%"`
	Siera                    sql.NullFloat64 `db:"SIERA" json:"SIERA"`
	Rs_per_9                 sql.NullFloat64 `db:"RS/9" json:"RS/9"`
	E_minues_f               sql.NullFloat64 `db:"E-F" json:"E-F"`
	Pace                     sql.NullFloat64 `db:"Pace" json:"Pace"`
	Ra9_minues_war           sql.NullFloat64 `db:"RA9-WAR" json:"RA9-WAR"`
	Bip_minues_wins          sql.NullFloat64 `db:"BIP-Wins" json:"BIP-Wins"`
	Lob_minues_wins          sql.NullFloat64 `db:"LOB-Wins" json:"LOB-Wins"`
	Fdp_minues_wins          sql.NullFloat64 `db:"FDP-Wins" json:"FDP-Wins"`
	Agerng                   sql.NullString  `db:"Age Rng" json:"Age Rng"`
	K_minues_bb_percent      sql.NullFloat64 `db:"K-BB%" json:"K-BB%"`
	Pull_percent             sql.NullFloat64 `db:"Pull%" json:"Pull%"`
	Cent_percent             sql.NullFloat64 `db:"Cent%" json:"Cent%"`
	Oppo_percent             sql.NullFloat64 `db:"Oppo%" json:"Oppo%"`
	Soft_percent             sql.NullFloat64 `db:"Soft%" json:"Soft%"`
	Med_percent              sql.NullFloat64 `db:"Med%" json:"Med%"`
	Hard_percent             sql.NullFloat64 `db:"Hard%" json:"Hard%"`
	Kwera                    sql.NullFloat64 `db:"kwERA" json:"kwERA"`
	Tto_percent              sql.NullFloat64 `db:"TTO%" json:"TTO%"`
	Frm                      sql.NullFloat64 `db:"FRM" json:"FRM"`
	K_per_9_plus             sql.NullFloat64 `db:"K/9+" json:"K/9+"`
	Bb_per_9_plus            sql.NullFloat64 `db:"BB/9+" json:"BB/9+"`
	K_per_bb_plus            sql.NullFloat64 `db:"K/BB+" json:"K/BB+"`
	H_per_9_plus             sql.NullFloat64 `db:"H/9+" json:"H/9+"`
	Hr_per_9_plus            sql.NullFloat64 `db:"HR/9+" json:"HR/9+"`
	Avg_plus                 sql.NullFloat64 `db:"AVG+" json:"AVG+"`
	Whip_plus                sql.NullFloat64 `db:"WHIP+" json:"WHIP+"`
	Babip_plus               sql.NullFloat64 `db:"BABIP+" json:"BABIP+"`
	Lob_percent_plus         sql.NullFloat64 `db:"LOB%+" json:"LOB%+"`
	K_percent_plus           sql.NullFloat64 `db:"K%+" json:"K%+"`
	Bb_percent_plus          sql.NullFloat64 `db:"BB%+" json:"BB%+"`
	Ld_percent_plus          sql.NullFloat64 `db:"LD%+" json:"LD%+"`
	Gb_percent_plus          sql.NullFloat64 `db:"GB%+" json:"GB%+"`
	Fb_percent_plus          sql.NullFloat64 `db:"FB%+" json:"FB%+"`
	Hr_per_fb_percent_plus   sql.NullFloat64 `db:"HR/FB%+" json:"HR/FB%+"`
	Pull_percent_plus        sql.NullFloat64 `db:"Pull%+" json:"Pull%+"`
	Cent_percent_plus        sql.NullFloat64 `db:"Cent%+" json:"Cent%+"`
	Oppo_percent_plus        sql.NullFloat64 `db:"Oppo%+" json:"Oppo%+"`
	Soft_percent_plus        sql.NullFloat64 `db:"Soft%+" json:"Soft%+"`
	Med_percent_plus         sql.NullFloat64 `db:"Med%+" json:"Med%+"`
	Hard_percent_plus        sql.NullFloat64 `db:"Hard%+" json:"Hard%+"`
	Ev                       sql.NullFloat64 `db:"EV" json:"EV"`
	La                       sql.NullFloat64 `db:"LA" json:"LA"`
	Barrels                  sql.NullFloat64 `db:"Barrels" json:"Barrels"`
	Barrel_percent           sql.NullFloat64 `db:"Barrel%" json:"Barrel%"`
	Maxev                    sql.NullFloat64 `db:"maxEV" json:"maxEV"`
	Hardhit                  sql.NullFloat64 `db:"HardHit" json:"HardHit"`
	Hardhit_percent          sql.NullFloat64 `db:"HardHit%" json:"HardHit%"`
	Events                   sql.NullFloat64 `db:"Events" json:"Events"`
	Cstr_percent             sql.NullFloat64 `db:"CStr%" json:"CStr%"`
	Csw_percent              sql.NullFloat64 `db:"CSW%" json:"CSW%"`
	Xera                     sql.NullFloat64 `db:"xERA" json:"xERA"`
	Botera                   sql.NullFloat64 `db:"botERA" json:"botERA"`
	Botovrch                 sql.NullFloat64 `db:"botOvrCH" json:"botOvrCH"`
	Botstfch                 sql.NullFloat64 `db:"botStfCH" json:"botStfCH"`
	Botcmdch                 sql.NullFloat64 `db:"botCmdCH" json:"botCmdCH"`
	Botovrcu                 sql.NullFloat64 `db:"botOvrCU" json:"botOvrCU"`
	Botstfcu                 sql.NullFloat64 `db:"botStfCU" json:"botStfCU"`
	Botcmdcu                 sql.NullFloat64 `db:"botCmdCU" json:"botCmdCU"`
	Botovrfa                 sql.NullFloat64 `db:"botOvrFA" json:"botOvrFA"`
	Botstffa                 sql.NullFloat64 `db:"botStfFA" json:"botStfFA"`
	Botcmdfa                 sql.NullFloat64 `db:"botCmdFA" json:"botCmdFA"`
	Botovrsi                 sql.NullFloat64 `db:"botOvrSI" json:"botOvrSI"`
	Botstfsi                 sql.NullFloat64 `db:"botStfSI" json:"botStfSI"`
	Botcmdsi                 sql.NullFloat64 `db:"botCmdSI" json:"botCmdSI"`
	Botovrsl                 sql.NullFloat64 `db:"botOvrSL" json:"botOvrSL"`
	Botstfsl                 sql.NullFloat64 `db:"botStfSL" json:"botStfSL"`
	Botcmdsl                 sql.NullFloat64 `db:"botCmdSL" json:"botCmdSL"`
	Botovrkc                 sql.NullFloat64 `db:"botOvrKC" json:"botOvrKC"`
	Botstfkc                 sql.NullFloat64 `db:"botStfKC" json:"botStfKC"`
	Botcmdkc                 sql.NullFloat64 `db:"botCmdKC" json:"botCmdKC"`
	Botovrfc                 sql.NullFloat64 `db:"botOvrFC" json:"botOvrFC"`
	Botstffc                 sql.NullFloat64 `db:"botStfFC" json:"botStfFC"`
	Botcmdfc                 sql.NullFloat64 `db:"botCmdFC" json:"botCmdFC"`
	Botovrfs                 sql.NullFloat64 `db:"botOvrFS" json:"botOvrFS"`
	Botstffs                 sql.NullFloat64 `db:"botStfFS" json:"botStfFS"`
	Botcmdfs                 sql.NullFloat64 `db:"botCmdFS" json:"botCmdFS"`
	Botovr                   sql.NullFloat64 `db:"botOvr" json:"botOvr"`
	Botstf                   sql.NullFloat64 `db:"botStf" json:"botStf"`
	Botcmd                   sql.NullFloat64 `db:"botCmd" json:"botCmd"`
	Botxrv100                sql.NullFloat64 `db:"botxRV100" json:"botxRV100"`
	Stf_plusch               sql.NullFloat64 `db:"Stf+CH" json:"Stf+CH"`
	Loc_plusch               sql.NullFloat64 `db:"Loc+CH" json:"Loc+CH"`
	Pit_plusch               sql.NullFloat64 `db:"Pit+CH" json:"Pit+CH"`
	Stf_pluscu               sql.NullFloat64 `db:"Stf+CU" json:"Stf+CU"`
	Loc_pluscu               sql.NullFloat64 `db:"Loc+CU" json:"Loc+CU"`
	Pit_pluscu               sql.NullFloat64 `db:"Pit+CU" json:"Pit+CU"`
	Stf_plusfa               sql.NullFloat64 `db:"Stf+FA" json:"Stf+FA"`
	Loc_plusfa               sql.NullFloat64 `db:"Loc+FA" json:"Loc+FA"`
	Pit_plusfa               sql.NullFloat64 `db:"Pit+FA" json:"Pit+FA"`
	Stf_plussi               sql.NullFloat64 `db:"Stf+SI" json:"Stf+SI"`
	Loc_plussi               sql.NullFloat64 `db:"Loc+SI" json:"Loc+SI"`
	Pit_plussi               sql.NullFloat64 `db:"Pit+SI" json:"Pit+SI"`
	Stf_plussl               sql.NullFloat64 `db:"Stf+SL" json:"Stf+SL"`
	Loc_plussl               sql.NullFloat64 `db:"Loc+SL" json:"Loc+SL"`
	Pit_plussl               sql.NullFloat64 `db:"Pit+SL" json:"Pit+SL"`
	Stf_pluskc               sql.NullFloat64 `db:"Stf+KC" json:"Stf+KC"`
	Loc_pluskc               sql.NullFloat64 `db:"Loc+KC" json:"Loc+KC"`
	Pit_pluskc               sql.NullFloat64 `db:"Pit+KC" json:"Pit+KC"`
	Stf_plusfc               sql.NullFloat64 `db:"Stf+FC" json:"Stf+FC"`
	Loc_plusfc               sql.NullFloat64 `db:"Loc+FC" json:"Loc+FC"`
	Pit_plusfc               sql.NullFloat64 `db:"Pit+FC" json:"Pit+FC"`
	Stf_plusfs               sql.NullFloat64 `db:"Stf+FS" json:"Stf+FS"`
	Loc_plusfs               sql.NullFloat64 `db:"Loc+FS" json:"Loc+FS"`
	Pit_plusfs               sql.NullFloat64 `db:"Pit+FS" json:"Pit+FS"`
	Stuff_plus               sql.NullFloat64 `db:"Stuff+" json:"Stuff+"`
	Location_plus            sql.NullFloat64 `db:"Location+" json:"Location+"`
	Pitching_plus            sql.NullFloat64 `db:"Pitching+" json:"Pitching+"`
	Stf_plusfo               sql.NullFloat64 `db:"Stf+FO" json:"Stf+FO"`
	Loc_plusfo               sql.NullFloat64 `db:"Loc+FO" json:"Loc+FO"`
	Pit_plusfo               sql.NullFloat64 `db:"Pit+FO" json:"Pit+FO"`
}
