package structs

import "database/sql"

type Batter struct {
	IDfg                   sql.NullInt16   `json:"IDfg" db:"IDfg"`
	Season                 sql.NullString  `json:"Season" db:"Season"`
	Name                   sql.NullString  `json:"Name" db:"Name"`
	Team                   sql.NullString  `json:"Team" db:"Team"`
	Age                    sql.NullInt16   `json:"Age" db:"Age"`
	G                      sql.NullInt16   `json:"G" db:"G"`
	AB                     sql.NullInt16   `json:"AB" db:"AB"`
	PA                     sql.NullInt16   `json:"PA" db:"PA"`
	H                      sql.NullInt16   `json:"H" db:"H"`
	Single                 sql.NullInt16   `json:"Single" db:"Single"`
	Double                 sql.NullInt16   `json:"Double" db:"Double"`
	Triple                 sql.NullInt16   `json:"Triple" db:"Triple"`
	HR                     sql.NullInt16   `json:"HR" db:"HR"`
	R                      sql.NullInt16   `json:"R" db:"R"`
	RBI                    sql.NullInt16   `json:"RBI" db:"RBI"`
	BB                     sql.NullInt16   `json:"BB" db:"BB"`
	IBB                    sql.NullInt16   `json:"IBB" db:"IBB"`
	SO                     sql.NullInt16   `json:"SO" db:"SO"`
	HBP                    sql.NullFloat64 `json:"HBP" db:"HBP"`
	SF                     sql.NullFloat64 `json:"SF" db:"SF"`
	SH                     sql.NullFloat64 `json:"SH" db:"SH"`
	GDP                    sql.NullFloat64 `json:"GDP" db:"GDP"`
	SB                     sql.NullFloat64 `json:"SB" db:"SB"`
	CS                     sql.NullFloat64 `json:"CS" db:"CS"`
	AVG                    sql.NullFloat64 `json:"AVG" db:"AVG"`
	GB                     sql.NullFloat64 `json:"GB" db:"GB"`
	FB                     sql.NullFloat64 `json:"FB" db:"FB"`
	LD                     sql.NullFloat64 `json:"LD" db:"LD"`
	IFFB                   sql.NullFloat64 `json:"IFFB" db:"IFFB"`
	Pitches                sql.NullFloat64 `json:"Pitches" db:"Pitches"`
	Balls                  sql.NullFloat64 `json:"Balls" db:"Balls"`
	Strikes                sql.NullFloat64 `json:"Strikes" db:"Strikes"`
	IFH                    sql.NullFloat64 `json:"IFH" db:"IFH"`
	BU                     sql.NullFloat64 `json:"BU" db:"BU"`
	BUH                    sql.NullFloat64 `json:"BUH" db:"BUH"`
	BB_percent             sql.NullFloat64 `json:"BB_percent" db:"BB_percent"`
	K_percent              sql.NullFloat64 `json:"K_percent" db:"K_percent"`
	BB_per_K               sql.NullFloat64 `json:"BB_per_K" db:"BB_per_K"`
	OBP                    sql.NullFloat64 `json:"OBP" db:"OBP"`
	SLG                    sql.NullFloat64 `json:"SLG" db:"SLG"`
	OPS                    sql.NullFloat64 `json:"OPS" db:"OPS"`
	ISO                    sql.NullFloat64 `json:"ISO" db:"ISO"`
	BABIP                  sql.NullFloat64 `json:"BABIP" db:"BABIP"`
	GB_per_FB              sql.NullFloat64 `json:"GB_per_FB" db:"GB_per_FB"`
	LD_percent             sql.NullFloat64 `json:"LD_percent" db:"LD_percent"`
	GB_percent             sql.NullFloat64 `json:"GB_percent" db:"GB_percent"`
	FB_percent             sql.NullFloat64 `json:"FB_percent" db:"FB_percent"`
	IFFB_percent           sql.NullFloat64 `json:"IFFB_percent" db:"IFFB_percent"`
	HR_per_FB              sql.NullFloat64 `json:"HR_per_FB" db:"HR_per_FB"`
	IFH_percent            sql.NullFloat64 `json:"IFH_percent" db:"IFH_percent"`
	BUH_percent            sql.NullFloat64 `json:"BUH_percent" db:"BUH_percent"`
	WOBA                   sql.NullFloat64 `json:"wOBA" db:"wOBA"`
	WRAA                   sql.NullFloat64 `json:"wRAA" db:"wRAA"`
	WRC                    sql.NullFloat64 `json:"wRC" db:"wRC"`
	Bat                    sql.NullFloat64 `json:"Bat" db:"Bat"`
	Fld                    sql.NullFloat64 `json:"Fld" db:"Fld"`
	Rep                    sql.NullFloat64 `json:"Rep" db:"Rep"`
	Pos                    sql.NullFloat64 `json:"Pos" db:"Pos"`
	RAR                    sql.NullFloat64 `json:"RAR" db:"RAR"`
	WAR                    sql.NullFloat64 `json:"WAR" db:"WAR"`
	Dol                    sql.NullString  `json:"Dol" db:"Dol"`
	Spd                    sql.NullFloat64 `json:"Spd" db:"Spd"`
	WRC_plus               sql.NullFloat64 `json:"wRC_plus" db:"wRC_plus"`
	WPA                    sql.NullFloat64 `json:"WPA" db:"WPA"`
	Plus_WPA               sql.NullFloat64 `json:"plus_WPA" db:"plus_WPA"`
	RE24                   sql.NullFloat64 `json:"RE24" db:"RE24"`
	REW                    sql.NullFloat64 `json:"REW" db:"REW"`
	PLI                    sql.NullFloat64 `json:"pLI" db:"pLI"`
	PhLI                   sql.NullFloat64 `json:"phLI" db:"phLI"`
	PH                     sql.NullFloat64 `json:"PH" db:"PH"`
	WPA_per_LI             sql.NullFloat64 `json:"WPA_per_LI" db:"WPA_per_LI"`
	Clutch                 sql.NullFloat64 `json:"Clutch" db:"Clutch"`
	FBv                    sql.NullFloat64 `json:"FBv" db:"FBv"`
	SL_percent             sql.NullFloat64 `json:"SL_percent" db:"SL_percent"`
	SLv                    sql.NullFloat64 `json:"SLv" db:"SLv"`
	CT_percent             sql.NullFloat64 `json:"CT_percent" db:"CT_percent"`
	CTv                    sql.NullFloat64 `json:"CTv" db:"CTv"`
	CB_percent             sql.NullFloat64 `json:"CB_percent" db:"CB_percent"`
	CBv                    sql.NullFloat64 `json:"CBv" db:"CBv"`
	CH_percent             sql.NullFloat64 `json:"CH_percent" db:"CH_percent"`
	CHv                    sql.NullFloat64 `json:"CHv" db:"CHv"`
	SF_percent             sql.NullFloat64 `json:"SF_percent" db:"SF_percent"`
	SFv                    sql.NullFloat64 `json:"SFv" db:"SFv"`
	KN_percent             sql.NullFloat64 `json:"KN_percent" db:"KN_percent"`
	KNv                    sql.NullFloat64 `json:"KNv" db:"KNv"`
	XX_percent             sql.NullFloat64 `json:"XX_percent" db:"XX_percent"`
	PO_percent             sql.NullFloat64 `json:"PO_percent" db:"PO_percent"`
	WFB                    sql.NullFloat64 `json:"wFB" db:"wFB"`
	WSL                    sql.NullFloat64 `json:"wSL" db:"wSL"`
	WCT                    sql.NullFloat64 `json:"wCT" db:"wCT"`
	WCB                    sql.NullFloat64 `json:"wCB" db:"wCB"`
	WCH                    sql.NullFloat64 `json:"wCH" db:"wCH"`
	WSF                    sql.NullFloat64 `json:"wSF" db:"wSF"`
	WKN                    sql.NullFloat64 `json:"wKN" db:"wKN"`
	WFB_per_C              sql.NullFloat64 `json:"wFB_per_C" db:"wFB_per_C"`
	WSL_per_C              sql.NullFloat64 `json:"wSL_per_C" db:"wSL_per_C"`
	WCT_per_C              sql.NullFloat64 `json:"wCT_per_C" db:"wCT_per_C"`
	WCB_per_C              sql.NullFloat64 `json:"wCB_per_C" db:"wCB_per_C"`
	CH_per_C               sql.NullFloat64 `json:"wCH_per_C" db:"wCH_per_C"`
	WSF_per_C              sql.NullFloat64 `json:"wSF_per_C" db:"wSF_per_C"`
	WKN_per_C              sql.NullFloat64 `json:"wKN_per_C" db:"wKN_per_C"`
	OSwing_percent         sql.NullFloat64 `json:"OSwing_percent" db:"OSwing_percent"`
	ZSwing_percent         sql.NullFloat64 `json:"ZSwing_percent" db:"ZSwing_percent"`
	Swing_percent          sql.NullFloat64 `json:"Swing_percent" db:"Swing_percent"`
	OContact_percent       sql.NullFloat64 `json:"OContact_percent" db:"OContact_percent"`
	ZContact_percent       sql.NullFloat64 `json:"ZContact_percent" db:"ZContact_percent"`
	Contact_percent        sql.NullFloat64 `json:"Contact_percent" db:"Contact_percent"`
	Zone_percent           sql.NullFloat64 `json:"Zone_percent" db:"Zone_percent"`
	FStrike_percent        sql.NullFloat64 `json:"FStrike_percent" db:"FStrike_percent"`
	SwStr_percent          sql.NullFloat64 `json:"SwStr_percent" db:"SwStr_percent"`
	BsR                    sql.NullFloat64 `json:"BsR" db:"BsR"`
	Pace                   sql.NullFloat64 `json:"Pace" db:"Pace"`
	Def                    sql.NullFloat64 `json:"Def" db:"Def"`
	WSB                    sql.NullFloat64 `json:"wSB" db:"wSB"`
	UBR                    sql.NullFloat64 `json:"UBR" db:"UBR"`
	Age_Rng                sql.NullString  `json:"Age Rng" db:"Age Rng"`
	Off                    sql.NullFloat64 `json:"Off" db:"Off"`
	Lg                     sql.NullFloat64 `json:"Lg" db:"Lg"`
	WGDP                   sql.NullFloat64 `json:"wGDP" db:"wGDP"`
	Pull_percent           sql.NullFloat64 `json:"Pull_percent" db:"Pull_percent"`
	Cent_percent           sql.NullFloat64 `json:"Cent_percent" db:"Cent_percent"`
	Oppo_percent           sql.NullFloat64 `json:"Oppo_percent" db:"Oppo_percent"`
	Soft_percent           sql.NullFloat64 `json:"Soft_percent" db:"Soft_percent"`
	Med_percent            sql.NullFloat64 `json:"Med_percent" db:"Med_percent"`
	Hard_percent           sql.NullFloat64 `json:"Hard_percent" db:"Hard_percent"`
	TTO_percent            sql.NullFloat64 `json:"TTO_percent" db:"TTO_percent"`
	FRM                    sql.NullFloat64 `json:"FRM" db:"FRM"`
	AVG_plus               sql.NullFloat64 `json:"AVG_plus" db:"AVG_plus"`
	BB_percent_plus        sql.NullFloat64 `json:"BB_percent_plus" db:"BB_percent_plus"`
	K_percent_plus         sql.NullFloat64 `json:"K_percent_plus" db:"K_percent_plus"`
	OBP_plus               sql.NullFloat64 `json:"OBP_plus" db:"OBP_plus"`
	SLG_plus               sql.NullFloat64 `json:"SLG_plus" db:"SLG_plus"`
	ISO_plus               sql.NullFloat64 `json:"ISO_plus" db:"ISO_plus"`
	BABIP_plus             sql.NullFloat64 `json:"BABIP_plus" db:"BABIP_plus"`
	LD_plus_percent        sql.NullFloat64 `json:"LD_plus_percent" db:"LD_plus_percent"`
	GB_percent_plus        sql.NullFloat64 `json:"GB_percent_plus" db:"GB_percent_plus"`
	FB_percent_plus        sql.NullFloat64 `json:"FB_percent_plus" db:"FB_percent_plus"`
	HR_per_FB_percent_plus sql.NullFloat64 `json:"HR_per_FB_percent_plus" db:"HR_per_FB_percent_plus"`
	Pull_percent_plus      sql.NullFloat64 `json:"Pull_percent_plus" db:"Pull_percent_plus"`
	Cent_percent_plus      sql.NullFloat64 `json:"Cent_percent_plus" db:"Cent_percent_plus"`
	Oppo_percent_plus      sql.NullFloat64 `json:"Oppo_percent_plus" db:"Oppo_percent_plus"`
	Soft_percent_plus      sql.NullFloat64 `json:"Soft_percent_plus" db:"Soft_percent_plus"`
	Med_percent_plus       sql.NullFloat64 `json:"Med_percent_plus" db:"Med_percent_plus"`
	Hard_percent_plus      sql.NullFloat64 `json:"Hard_percent_plus" db:"Hard_percent_plus"`
	EV                     sql.NullFloat64 `json:"EV" db:"EV"`
	LA                     sql.NullFloat64 `json:"LA" db:"LA"`
	Barrels                sql.NullFloat64 `json:"Barrels" db:"Barrels"`
	Barrel_percent         sql.NullFloat64 `json:"Barrel_percent" db:"Barrel_percent"`
	MaxEV                  sql.NullFloat64 `json:"maxEV" db:"maxEV"`
	HardHit                sql.NullFloat64 `json:"HardHit" db:"HardHit"`
	HardHit_percent        sql.NullFloat64 `json:"HardHit_percent" db:"HardHit_percent"`
	CStr_percent           sql.NullFloat64 `json:"CStr_percent" db:"CStr_percent"`
	CSW_percent            sql.NullFloat64 `json:"CSW_percent" db:"CSW_percent"`
	XBA                    sql.NullFloat64 `json:"xBA" db:"xBA"`
	XSLG                   sql.NullFloat64 `json:"xSLG" db:"xSLG"`
	XwOBA                  sql.NullFloat64 `json:"xwOBA" db:"xwOBA"`
}
